apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: cicd
  labels:
    app: keycloak
    component: ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Proto: "https"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Host: "keycloak.team1.devops.pmifi.ru"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Port: "443"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-For: "$proxy_add_x_forwarded_for"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Real-IP: "$remote_addr"
spec:
  tls:
    - hosts:
        - keycloak.team1.devops.pmifi.ru
      secretName: multi-domain-tls
  rules:
    - host: keycloak.team1.devops.pmifi.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
