apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docker-registry-ingress
  namespace: docker-registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Proto: "https"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Host: "registry.team1.devops.pmifi.ru"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-Port: "443"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Forwarded-For: "$proxy_add_x_forwarded_for"
    traefik.ingress.kubernetes.io/headers.customrequestheaders.X-Real-IP: "$remote_addr"
    traefik.ingress.kubernetes.io/service.serverstransport: traefik-default@kubernetescrd
spec:
  tls:
    - hosts:
        - registry.team1.devops.pmifi.ru
      secretName: multi-domain-tls  
  rules:
    - host: registry.team1.devops.pmifi.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docker-registry
                port:
                  number: 5000